table 'Table 1 (Orders)'
	lineageTag: d14272b3-f1e1-489e-a12a-187eeb07cc85

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 866e1c5b-1700-41cc-84f7-51a6897c326f
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: df37697c-0bb2-457b-9657-3b986324df2e
			defaultHierarchy: LocalDateTable_3e10a35a-e1a1-429f-86c5-a3a3204cc0a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 0860e24c-19a7-4ad5-9d70-f242709471a7
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition 'Table 1 (Orders)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\UNO\Downloads\SuperStoreUS-2015.xlsx"), null, false),
				    Orders_sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Removed Other Columns" = Table.SelectColumns(Orders_sheet, List.Select(Table.ColumnNames(Orders_sheet), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(Orders_sheet, _))) otherwise true)),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order Priority", type text}, {"Discount", type number}, {"Unit Price", type number}, {"Shipping Cost", type number}, {"Customer ID", Int64.Type}, {"Customer Name", type text}, {"Ship Mode", type text}, {"Customer Segment", type text}, {"Product Category", type text}, {"Product Sub-Category", type text}, {"Product Container", type text}, {"Product Name", type text}, {"Product Base Margin", type number}, {"Country", type text}, {"Region", type text}, {"State or Province", type text}, {"City", type text}, {"Postal Code", Int64.Type}, {"Order Date", type date}, {"Ship Date", type date}, {"Profit", type number}, {"Quantity ordered new", Int64.Type}, {"Sales", type number}, {"Order ID", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Not Specified","n/a",Replacer.ReplaceText,{"Order Priority"}),
				    #"Grouped Rows" = Table.Group(#"Replaced Value", {"Order Date"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Order Date", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

